# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'guiForScript.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(672, 368)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 641, 351))
        self.tabWidget.setObjectName("tabWidget")
        self.processTab = QtWidgets.QWidget()
        self.processTab.setObjectName("processTab")
        self.label = QtWidgets.QLabel(self.processTab)
        self.label.setGeometry(QtCore.QRect(10, 20, 41, 21))
        self.label.setObjectName("label")
        self.labelFileName = QtWidgets.QLabel(self.processTab)
        self.labelFileName.setGeometry(QtCore.QRect(50, 20, 431, 21))
        self.labelFileName.setObjectName("labelFileName")
        self.pushButtonLoadFile = QtWidgets.QPushButton(self.processTab)
        self.pushButtonLoadFile.setGeometry(QtCore.QRect(500, 20, 89, 25))
        self.pushButtonLoadFile.setObjectName("pushButtonLoadFile")
        self.listWidgetFeatures = QtWidgets.QListWidget(self.processTab)
        self.listWidgetFeatures.setGeometry(QtCore.QRect(10, 120, 261, 191))
        self.listWidgetFeatures.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidgetFeatures.setObjectName("listWidgetFeatures")
        self.comboBoxGrainSize = QtWidgets.QComboBox(self.processTab)
        self.comboBoxGrainSize.setGeometry(QtCore.QRect(90, 50, 111, 25))
        self.comboBoxGrainSize.setObjectName("comboBoxGrainSize")
        self.comboBoxGrainSize.addItem("")
        self.comboBoxGrainSize.addItem("")
        self.comboBoxGrainSize.addItem("")
        self.label_2 = QtWidgets.QLabel(self.processTab)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.processTab)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 81, 21))
        self.label_3.setObjectName("label_3")
        self.listWidgetSelectedFeatures = QtWidgets.QListWidget(self.processTab)
        self.listWidgetSelectedFeatures.setGeometry(QtCore.QRect(320, 120, 261, 101))
        self.listWidgetSelectedFeatures.setObjectName("listWidgetSelectedFeatures")
        self.label_4 = QtWidgets.QLabel(self.processTab)
        self.label_4.setGeometry(QtCore.QRect(320, 90, 211, 21))
        self.label_4.setObjectName("label_4")
        self.pushButtonFilterFeatures = QtWidgets.QPushButton(self.processTab)
        self.pushButtonFilterFeatures.setGeometry(QtCore.QRect(320, 230, 111, 25))
        self.pushButtonFilterFeatures.setObjectName("pushButtonFilterFeatures")
        self.pushButtonPerformPCA = QtWidgets.QPushButton(self.processTab)
        self.pushButtonPerformPCA.setGeometry(QtCore.QRect(320, 260, 161, 25))
        self.pushButtonPerformPCA.setObjectName("pushButtonPerformPCA")
        self.tabWidget.addTab(self.processTab, "")
        self.playTab = QtWidgets.QWidget()
        self.playTab.setObjectName("playTab")
        self.readPoint = QtWidgets.QSlider(self.playTab)
        self.readPoint.setGeometry(QtCore.QRect(30, 240, 581, 61))
        self.readPoint.setOrientation(QtCore.Qt.Horizontal)
        self.readPoint.setObjectName("readPoint")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.playTab)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(530, 150, 71, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.playButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.playButton.setObjectName("playButton")
        self.verticalLayout.addWidget(self.playButton)
        self.stopButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.verticalLayout.addWidget(self.stopButton)
        self.comboBoxGrainSortingCriterion = QtWidgets.QComboBox(self.playTab)
        self.comboBoxGrainSortingCriterion.setGeometry(QtCore.QRect(30, 40, 221, 25))
        self.comboBoxGrainSortingCriterion.setObjectName("comboBoxGrainSortingCriterion")
        self.comboBoxLookUpDirection = QtWidgets.QComboBox(self.playTab)
        self.comboBoxLookUpDirection.setGeometry(QtCore.QRect(270, 40, 111, 25))
        self.comboBoxLookUpDirection.setObjectName("comboBoxLookUpDirection")
        self.comboBoxLookUpDirection.addItem("")
        self.comboBoxLookUpDirection.addItem("")
        self.label_5 = QtWidgets.QLabel(self.playTab)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 141, 21))
        self.label_5.setObjectName("label_5")
        self.comboBoxWindowType = QtWidgets.QComboBox(self.playTab)
        self.comboBoxWindowType.setGeometry(QtCore.QRect(30, 110, 121, 25))
        self.comboBoxWindowType.setObjectName("comboBoxWindowType")
        self.comboBoxWindowType.addItem("")
        self.comboBoxWindowType.addItem("")
        self.comboBoxWindowType.addItem("")
        self.comboBoxWindowType.addItem("")
        self.comboBoxWindowType.addItem("")
        self.comboBoxWindowType.addItem("")
        self.label_6 = QtWidgets.QLabel(self.playTab)
        self.label_6.setGeometry(QtCore.QRect(30, 80, 121, 21))
        self.label_6.setObjectName("label_6")
        self.pushButtonRearrange = QtWidgets.QPushButton(self.playTab)
        self.pushButtonRearrange.setGeometry(QtCore.QRect(180, 110, 271, 25))
        self.pushButtonRearrange.setObjectName("pushButtonRearrange")
        self.pushButtonOriginalOrder = QtWidgets.QPushButton(self.playTab)
        self.pushButtonOriginalOrder.setGeometry(QtCore.QRect(188, 160, 261, 25))
        self.pushButtonOriginalOrder.setObjectName("pushButtonOriginalOrder")
        self.tabWidget.addTab(self.playTab, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Corpus Based Concatenative Synth"))
        self.label.setText(_translate("Dialog", "File :"))
        self.labelFileName.setText(_translate("Dialog", "TextLabel"))
        self.pushButtonLoadFile.setText(_translate("Dialog", "Load File"))
        self.comboBoxGrainSize.setItemText(0, _translate("Dialog", "16384"))
        self.comboBoxGrainSize.setItemText(1, _translate("Dialog", "8192"))
        self.comboBoxGrainSize.setItemText(2, _translate("Dialog", "4096"))
        self.label_2.setText(_translate("Dialog", "Grain Size:"))
        self.label_3.setText(_translate("Dialog", "Features"))
        self.label_4.setText(_translate("Dialog", "Selected Features"))
        self.pushButtonFilterFeatures.setText(_translate("Dialog", "Filter Features"))
        self.pushButtonPerformPCA.setText(_translate("Dialog", "Perform PCA "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.processTab), _translate("Dialog", "Process"))
        self.playButton.setText(_translate("Dialog", "play"))
        self.stopButton.setText(_translate("Dialog", "stop"))
        self.comboBoxLookUpDirection.setItemText(0, _translate("Dialog", "Ascending"))
        self.comboBoxLookUpDirection.setItemText(1, _translate("Dialog", "Descending"))
        self.label_5.setText(_translate("Dialog", "Sorty by:"))
        self.comboBoxWindowType.setItemText(0, _translate("Dialog", "hanning"))
        self.comboBoxWindowType.setItemText(1, _translate("Dialog", "hamming"))
        self.comboBoxWindowType.setItemText(2, _translate("Dialog", "blackman"))
        self.comboBoxWindowType.setItemText(3, _translate("Dialog", "gaussian"))
        self.comboBoxWindowType.setItemText(4, _translate("Dialog", "welch"))
        self.comboBoxWindowType.setItemText(5, _translate("Dialog", "bartlett"))
        self.label_6.setText(_translate("Dialog", "Window type:"))
        self.pushButtonRearrange.setText(_translate("Dialog", "<< rEaRrAnGe!! >> : P"))
        self.pushButtonOriginalOrder.setText(_translate("Dialog", "Normal  : \'("))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.playTab), _translate("Dialog", "Play"))


